CXX = g++
CXXFLAGS = -Wall -O2

all: ordenacionIterativa

ordenacion: ordenacionIterativa.cpp
	$(CXX) $(CXXFLAGS) ordenacionIterativa.cpp -o ordenacionIterativa

clean:
	rm -f ordenacionIterativa tiempos_*.dat