CXX = g++
CXXFLAGS = -Wall -O2

all: multiplicacionMatrices.exe

multiplicacionMatrices.exe: multiplicacionMatrices.cpp
	$(CXX) $(CXXFLAGS) $< -o $@

clean:
	rm -f multiplicacionMatrices.exe multiplicacionMatrices.dat
