CXX = g++
CXXFLAGS = -Wall -O2

all: comparacionBusquedas.exe

comparacionBusquedas.exe: comparacionBusquedas.cpp
	$(CXX) $(CXXFLAGS) $< -o $@

clean:
	rm -f comparacionBusquedas.exe tiemposBusqueda.dat
